### ISSUE TITLE
How to convert pressure into a Air Speed in km/h

### ISSUE THREAD

**Issue by pierrotm777** [bolderflight/ms4525do#1]
Hello,

I work on a telemetry for my Calmato RC plane.

Can you explain me how to convert your result to a km/h speed please ?

Thanks,

Pierre

**Comment by flybrianfly** [comment]
The [MS4525DO library](https://github.com/bolderflight/ms4525do) is built to return the pressure from the sensor in units of Pa. We have an [open-source air data library](https://github.com/bolderflight/airdata) which can use the measured pressure to compute indicated airspeed in m/s using the *Ias_mps* function. Finally, you would need to convert m/s to km/h by multiplying the airspeed by 3.6.
