### ISSUE TITLE
My code reurn negatives values

### ISSUE THREAD

**Issue by pierrotm777** [bolderflight/ms4525do#2]
Hello,

Thanks for this library.
I try to build a telemetry for my RC plane and my MS4525DO return me negatives values.
My code is:

```
void MS4525DO_Init() {
  pres.Config(&Wire1, 0x28, 1.0f, -1.0f);
  if (pres.Begin())
    MS4525DOAvailable = true;
  else
    MS4525DOAvailable = false;
}

float MS4525() {
  /* Read the sensor */
  if (pres.Read()) {
    pressionMS4525 = pres.pres_pa();//*3.6 for km/h
    if (printPITOT == true)
    {
      /* Display the data */
      Serial.print(pressionMS4525, 2);
      Serial.print("\t");
      Serial.print(pres.die_temp_c());
      Serial.println("°C\r\n");  
    }
  }
  return pressionMS4525;
}
```

The sensor don't move and this code return me:
-140.46	27.67°C

It's normal ?

Thanks for your help,

Pierre

**Comment by flybrianfly** [comment]
Negative values are valid, it depends on which of the pressure ports has higher pressure. A lot of the autopilot implementations will estimate and remove the startup bias. They will then take the absolute value for estimating airspeed so it doesn't matter which way the tubing is connected to the sensor.
