### ISSUE TITLE
Explanation of method for determining pres_cnts_ and temp_cnts_?

### ISSUE THREAD

**Issue by joshgalvan** [bolderflight/ms4525do#3]
I understand that the formula used to determine the pressure in PSI and temperature is from the "PRESSURE AND TEMPERATURE TRANSFER FUNCTION" section of the datasheet, rearranged to solve for the pressure or temperature, but I can't tell how you determined the pres_cnts_ and temp_cnts_, or where you derived the formula from. Could you please help me with this? Thank you!

**Comment by flybrianfly** [comment]
If you read through the [Interface Document](https://github.com/bolderflight/ms4525do/blob/main/docs/I2C-Interface-to-Digital-Pressure-Sensors-AMSYS-an802e.pdf), you'll see that the pressure data is 14 bits, temperature data is 11 bits, and there is also a status bit that is sent. The count code is simply using bit shifting and masking to pull the pressure data, temperature data, and status out of the four bytes (32 bits) that it is encoded into.

**Comment by joshgalvan** [comment]
I took another look at it, thank you! Makes sense to me now. For some reason I missed that it was outputting the count and thought you were deriving it somehow.
